root: ./docs
structure:
  readme: README.md
  summary: SUMMARY.md
redirects:
  frontend/: features/frontend/README.md
  backend/: features/backend/README.md
  guides/getting-started: guides/project-overview.md
  architecture/: architecture/README.md
  reference/: reference/README.md
  processes/: processes/README.md
  routes/: routes/README.md 