/**
 * Index file for component exports
 * Generated by update-shadcn-index.mjs
 */

export * from './Icon';
export * from './IconContext';
export * from './IconUtils';
export * from './icons';
export * from './index';
export * from './registry-loader';
export * from './semantic-map';
export * from './types';
export * from './adapters';
