// AUTO-GENERATED by scripts/generate-preview-pages.ts - DO NOT EDIT MANUALLY!
// Timestamp: 2025-04-09T22:15:17.838Z

import React from 'react';
import Link from 'next/link';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { Input } from '../../../../../../components/ui/input';
import { Label } from '@/components/ui/label';

const statusStyles: Record<string, string> = {
  stable: 'bg-green-100 text-green-800 border-green-200',
  beta: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  deprecated: 'bg-red-100 text-red-800 border-red-200',
  development: 'bg-blue-100 text-blue-800 border-blue-200',
};

export default function InputPreviewPage() {
  const componentMeta = {
    name: 'Input',
    description: 'A standard text input field.',
    category: 'atom',
    subcategory: 'input',
    renderType: 'server',
    author: 'Shadcn',
    since: '2023-01-01',
    status: 'stable',
  };
  const examples: string[] = [];

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Breadcrumbs */}
      <nav aria-label="Breadcrumb" className="mb-6 text-sm text-secondary">
        <ol className="list-none p-0 inline-flex space-x-2">
          <li className="flex items-center">
            <Link href="/debug-tools/ui-components" className="hover:text-Interactive">
              UI Components
            </Link>
          </li>
          <li className="flex items-center">
            <span className="mx-2">/</span>
            <span className="capitalize">{componentMeta.category}</span>
          </li>
          {componentMeta.subcategory && (
            <li className="flex items-center">
              <span className="mx-2">/</span>
              <span className="capitalize">{componentMeta.subcategory}</span>
            </li>
          )}
          <li className="flex items-center">
            <span className="mx-2">/</span>
            <span className="font-medium text-primary">{componentMeta.name}</span>
          </li>
        </ol>
      </nav>

      {/* Header Section */}
      <div className="mb-8 border-b border-divider pb-4">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
          <h1 className="text-3xl font-bold text-primary mb-2 sm:mb-0">{componentMeta.name}</h1>
          <div className="flex items-center space-x-3 text-sm">
            {componentMeta.status && (
              <Badge
                variant="outline"
                className={cn(
                  'font-medium',
                  statusStyles[componentMeta.status] || statusStyles.development
                )}
              >
                {componentMeta.status}
              </Badge>
            )}
            <span className="text-secondary capitalize">({componentMeta.renderType || 'N/A'})</span>
          </div>
        </div>
        {componentMeta.description && (
          <p className="mt-2 text-secondary max-w-3xl">{componentMeta.description}</p>
        )}
        <div className="mt-3 flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted-foreground">
          {componentMeta.author && <span>Author: {componentMeta.author}</span>}
          {componentMeta.since && <span>Since: {componentMeta.since}</span>}
        </div>
      </div>

      {/* Examples Section (Rendering the actual component) */}
      <div className="mb-8">
        <h2 className="text-xl font-semibold mb-4 text-primary">Examples / Usage</h2>
        <div className="space-y-8">
          {/* ---- ADD YOUR RENDERING EXAMPLES MANUALLY BELOW ---- */}

          {/* Example 1: Different Input Types */}
          <div className="border border-divider rounded-lg p-6">
            <h3 className="text-lg font-medium mb-4">Input Types</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="text-input">Text (Default)</Label>
                <Input id="text-input" type="text" placeholder="Enter text..." />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password-input">Password</Label>
                <Input id="password-input" type="password" placeholder="Enter password" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email-input">Email</Label>
                <Input id="email-input" type="email" placeholder="email@example.com" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="number-input">Number</Label>
                <Input id="number-input" type="number" placeholder="Enter a number" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tel-input">Telephone</Label>
                <Input id="tel-input" type="tel" placeholder="123-456-7890" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="url-input">URL</Label>
                <Input id="url-input" type="url" placeholder="https://example.com" />
              </div>
            </div>
          </div>

          {/* Example 2: Disabled State */}
          <div className="border border-divider rounded-lg p-6">
            <h3 className="text-lg font-medium mb-4">Disabled State</h3>
            <div className="space-y-2">
              <Label htmlFor="disabled-input">Disabled Input</Label>
              <Input id="disabled-input" type="text" placeholder="Cannot type here" disabled />
            </div>
          </div>

          {/* Example 3: With Label */}
          <div className="border border-divider rounded-lg p-6">
            <h3 className="text-lg font-medium mb-4">Usage with Label</h3>
            <div className="grid w-full max-w-sm items-center gap-1.5">
              <Label htmlFor="email-labeled">Email</Label>
              <Input type="email" id="email-labeled" placeholder="Email" />
            </div>
          </div>

          {/* Example 4: File Input (Specific Styling) */}
          {/* Note: Input component styles file inputs via file: pseudo-element */}
          <div className="border border-divider rounded-lg p-6">
            <h3 className="text-lg font-medium mb-4">File Input</h3>
            <div className="grid w-full max-w-sm items-center gap-1.5">
              <Label htmlFor="picture">Picture</Label>
              <Input id="picture" type="file" />
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              Styling applied via `file:` Tailwind modifier in component.
            </p>
          </div>

          {/* ---- END MANUAL EXAMPLES ---- */}
        </div>
      </div>

      {/* Code Snippets Section - REMOVE as examples are now inline */}
      {/* {examples && examples.length > 0 && ( ... )} */}
    </div>
  );
}
