/**
 * Index file for component exports
 * Generated by update-shadcn-index.mjs
 */

export * from './FormFieldSkeleton';
export * from './LoadingSkeleton';
export * from './Skeleton';
export * from './SkeletonSection';
export * from './examples';

// Explicitly export these components for proper tree-shaking
export { 
  UIFormSkeleton as FormSkeleton,
  UIDashboardSkeleton as DashboardSkeleton,
  UICampaignDetailSkeleton as CampaignDetailSkeleton
} from './LoadingSkeleton';
