name: Deployment

on:
  workflow_run:
    workflows: ['Tests', 'Lint', 'E2E Tests']
    branches: [main]
    types: [completed]

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.justify.social

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run performance tests
        run: node scripts/consolidated/testing/measure-bundle-size.js

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          # Add actual deployment command here, e.g.
          # npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
          fi

  deploy-production:
    name: Deploy to Production
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://justify.social

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run performance tests
        run: node scripts/consolidated/testing/measure-bundle-size.js

      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          # Add actual deployment command here, e.g.
          # npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run post-deployment verification
        run: node scripts/consolidated/testing/verify-deployment.js
