name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx --max-warnings=0
        
      - name: Check for 'any' type usage
        run: node scripts/consolidated/linting/find-any-types.js
        
      - name: Check for <img> tag usage
        run: node scripts/consolidated/linting/find-img-tags.js
        
      - name: Check for React Hook dependency issues
        run: node scripts/consolidated/linting/find-hook-issues.js

      - name: Upload linter reports
        uses: actions/upload-artifact@v3
        with:
          name: linter-reports
          path: |
            any-types-report.txt
            img-tags-report.txt
            hook-issues-report.txt 