name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Check for 'any' type usage
        run: |
          echo "Checking for 'any' type usage..."
          node src/scripts/find-any-types.js --path=src/
          
      - name: Check for <img> tag usage
        run: |
          echo "Checking for <img> tag usage..."
          node src/scripts/find-img-tags.js --path=src/
          
      - name: Check for React Hook dependency issues
        run: |
          echo "Checking for React Hook dependency issues..."
          node src/scripts/find-hook-issues.js --path=src/

      - name: Upload linter reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linter-reports
          path: |
            any-type-usage-report.md
            img-tag-usage-report.md
            hook-dependency-issues-report.md 